uTRAP romfs has been updated.

diff --git a/ROMFS/trapfmu/init.d/rcS b/ROMFS/trapfmu/init.d/rcS
--- a/ROMFS/trapfmu/init.d/rcS
+++ b/ROMFS/trapfmu/init.d/rcS
@@ -3,7 +3,7 @@
 set +e
 # Un comment the line below to help debug scripts by printing a trace of the script commands
 #set -x
-# TRAPFMU startup script.
+# PX4FMU startup script.
 #
 # NOTE: environment variable references:
 #    If the dollar sign ('$') is followed by a left bracket ('{') then the
@@ -21,34 +21,19 @@ set +e
 # it wastes flash
 #
 set R /
-set AUTOCNF no
 set FCONFIG /fs/microsd/etc/config.txt
 set FEXTRAS /fs/microsd/etc/extras.txt
 set FRC /fs/microsd/etc/rc.txt
 set IOFW "/etc/extras/stalya_io-v2_default.bin"
-set IO_PRESENT yes
 set LOGGER_ARGS ""
 set LOGGER_BUF 8
-set MIXER none
-set MIXER_AUX none
-set MIXER_FILE none
-set MIXER_EXTRA none
-set OUTPUT_MODE none
 set PARAM_FILE ""
-set PWM_OUT none
-set PWM_MAIN_RATE p:PWM_MAIN_RATE
-set PWM_AUX_OUT none
-set PWM_AUX_RATE p:PWM_AUX_RATE
-set PWM_EXTRA_OUT none
-set PWM_EXTRA_RATE p:PWM_EXTRA_RATE
-set EXTRA_MIXER_MODE none
+set PARAM_BACKUP_FILE ""
 set RC_INPUT_ARGS ""
 set SDCARD_AVAILABLE no
 set SDCARD_EXT_PATH /fs/microsd/ext_autostart
 set SDCARD_FORMAT no
-set SDCARD_MIXERS_PATH /fs/microsd/etc/mixers
 set STARTUP_TUNE 1
-set USE_IO no
 set VEHICLE_TYPE none
 
 #
@@ -109,6 +94,7 @@ then
 	fi
 
 	set PARAM_FILE /fs/microsd/params
+	set PARAM_BACKUP_FILE "/fs/microsd/parameters_backup.bson"
 fi
 
 #
@@ -144,31 +130,36 @@ else
 		echo "ERROR [init] param import failed"
 		set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
 
-		param dump $PARAM_FILE
+		bsondump $PARAM_FILE
 
 		if [ -d "/fs/microsd" ]
 		then
-			dmesg >> /fs/microsd/param_import_fail.txt &
-
 			# try to make a backup copy
-			cp $PARAM_FILE /fs/microsd/param_import_fail.bson &
-		fi
+			cp $PARAM_FILE /fs/microsd/param_import_fail.bson
 
-		# try importing from backup file
-		if [ -f "/fs/microsd/parameters_backup.bson" ]
-		then
-			echo "[init] importing from parameter backup"
+			# try importing from backup file
+			if [ -f $PARAM_BACKUP_FILE ]
+			then
+				echo "[init] importing from parameter backup"
 
-			# dump current backup file contents for comparison
-			param dump /fs/microsd/parameters_backup.bson
+				# dump current backup file contents for comparison
+				bsondump $PARAM_BACKUP_FILE
 
-			param import /fs/microsd/parameters_backup.bson
+				param import $PARAM_BACKUP_FILE
+
+				# overwrite invalid $PARAM_FILE with backup
+				cp $PARAM_BACKUP_FILE $PARAM_FILE
+			fi
+
+			param status
+
+			dmesg >> /fs/microsd/param_import_fail.txt &
 		fi
 	fi
 
 	if [ $SDCARD_AVAILABLE = yes ]
 	then
-		param select-backup /fs/microsd/parameters_backup.bson
+		param select-backup $PARAM_BACKUP_FILE
 	fi
 
 	if ver hwcmp PX4_FMU_V5X PX4_FMU_V6X ARK_FMU_V6X
@@ -177,13 +168,12 @@ else
 	fi
 
 	#
-	# Set AUTOCNF flag to use it in AUTOSTART scripts.
+	# If the airframe has been previously reset SYS_AUTCONFIG will have been set to 1 and other params will be reset on the next boot.
 	#
 	if param greater SYS_AUTOCONFIG 0
 	then
-		# Wipe out params except RC*, flight modes, total flight time, calibration parameters, next flight UUID
-		param reset_all SYS_AUTO* RC* COM_FLTMODE* LND_FLIGHT* TC_* CAL_ACC* CAL_GYRO* COM_FLIGHT*
-		set AUTOCNF yes
+		# Reset params except Airframe, RC calibration, sensor calibration, flight modes, total flight time, and next flight UUID.
+		param reset_all SYS_AUTOSTART RC* CAL_* COM_FLTMODE* LND_FLIGHT* TC_* COM_FLIGHT*
 	fi
 
 	#
@@ -209,6 +199,26 @@ else
 	unset BOARD_RC_DEFAULTS
 
 	#
+	# Set parameters and env variables for selected SYS_AUTOSTART.
+	#
+	set AUTOSTART_PATH etc/init.d/rc.autostart
+	if ! param compare SYS_AUTOSTART 0
+	then
+		if param greater SYS_AUTOSTART 1000000
+		then
+			# Use external startup file
+			if [ $SDCARD_AVAILABLE = yes ]
+			then
+				set AUTOSTART_PATH etc/init.d/rc.autostart_ext
+			else
+				echo "ERROR [init] SD card not mounted - trying to load airframe from ROMFS"
+			fi
+		fi
+		. ${R}$AUTOSTART_PATH
+	fi
+	unset AUTOSTART_PATH
+
+	#
 	# Start the tone_alarm driver.
 	# Needs to be started after the parameters are loaded (for CBRK_BUZZER).
 	#
@@ -218,7 +228,7 @@ else
 	# Waypoint storage.
 	# REBOOTWORK this needs to start in parallel.
 	#
-	if param compare SYS_DM_BACKEND 1
+	if param compare -s SYS_DM_BACKEND 1
 	then
 		dataman start -r
 	else
@@ -244,31 +254,15 @@ else
 	#
 	rgbled start -X -q
 	rgbled_ncp5623c start -X -q
+	rgbled_lp5562 start -X -q
+	rgbled_is31fl3195 start -X -q
 
 	#
 	# Start the I/O expender driver before the PX4IO driver !!!
 	#
 	pca9557 -I -b 2 start
 
-	#
-	# Set parameters and env variables for selected AUTOSTART.
-	#
-	set AUTOSTART_PATH etc/init.d/rc.autostart
-	if ! param compare SYS_AUTOSTART 0
-	then
-		if param greater SYS_AUTOSTART 1000000
-		then
-			# Use external startup file
-			if [ $SDCARD_AVAILABLE = yes ]
-			then
-				set AUTOSTART_PATH etc/init.d/rc.autostart_ext
-			else
-				echo "ERROR [init] SD card not mounted - trying to load airframe from ROMFS"
-			fi
-		fi
-		. ${R}$AUTOSTART_PATH
-	fi
-	unset AUTOSTART_PATH
+
 
 	#
 	# Override parameters from user configuration file.
@@ -280,30 +274,15 @@ else
 	fi
 
 	#
-	# If autoconfig parameter was set, reset it and save parameters.
+	# Start IO for PWM output or RC input if enabled
 	#
-	if [ $AUTOCNF = yes ]
+	if param compare -s SYS_USE_IO 1
 	then
-		param set SYS_AUTOCONFIG 0
-	fi
-
-	#
-	# Check if PX4IO present and update firmware if needed.
-	# Assumption IOFW set to firmware file and IO_PRESENT = no
-	#
-
-	if [ -f $IOFW ]
-	then
-		# Check for the mini using build with px4io fw file
-		# but not a px4IO
-		if ver hwtypecmp V540 V560
+		# Check if PX4IO present and update firmware if needed.
+		if [ -f $IOFW ]
 		then
-			param set SYS_USE_IO 0
-		else
-			if px4io checkcrc ${IOFW}
+			if ! px4io checkcrc ${IOFW}
 			then
-				set IO_PRESENT yes
-			else
 				# tune Program PX4IO
 				tune_control play -t 16 # tune 16 = PROG_PX4IO
 
@@ -314,7 +293,6 @@ else
 					if px4io checkcrc ${IOFW}
 					then
 						tune_control play -t 17 # tune 17 = PROG_PX4IO_OK
-						set IO_PRESENT yes
 					else
 						tune_control play -t 18 # tune 18 = PROG_PX4IO_ERR
 					fi
@@ -323,20 +301,12 @@ else
 				fi
 			fi
 		fi
-	fi
 
-	#
-	# Set USE_IO flag.
-	#
-	if param compare -s SYS_USE_IO 1
-	then
-		set USE_IO yes
-	fi
-
-	if [ $USE_IO = yes -a $IO_PRESENT = no ]
-	then
-		echo "PX4IO not found"
-		set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
+		if ! px4io start
+		then
+			echo "PX4IO start failed"
+			set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
+		fi
 	fi
 
 	#
@@ -346,13 +316,38 @@ else
 	rc_update start
 	manual_control start
 
+	# Start camera trigger, capture and PPS before pwm_out as they might access
+	# pwm pins
+	if param greater -s TRIG_MODE 0
+	then
+		camera_trigger start
+		camera_feedback start
+	fi
+	# PPS capture driver
+	if param greater -s PPS_CAP_ENABLE 0
+	then
+		pps_capture start
+	fi
+	# Camera capture driver
+	if param greater -s CAM_CAP_FBACK 0
+	then
+		if camera_capture start
+		then
+			camera_capture on
+		fi
+	fi
+
 	#
 	# Sensors System (start before Commander so Preflight checks are properly run).
 	# Commander needs to be this early for in-air-restarts.
 	#
 	if param greater SYS_HITL 0
 	then
-		set OUTPUT_MODE hil
+		if ! pwm_out_sim start -m hil
+		then
+			tune_control play error
+		fi
+
 		sensors start -h
 		commander start -h
 		# disable GPS
@@ -361,7 +356,10 @@ else
 		# start the simulator in hardware if needed
 		if param compare SYS_HITL 2
 		then
-			sih start
+			simulator_sih start
+			sensor_baro_sim start
+			sensor_mag_sim start
+			sensor_gps_sim start
 		fi
 
 	else
@@ -390,25 +388,20 @@ else
 
 		sensors start
 		commander start
+
+		dshot start
+		pwm_out start
 	fi
 
 	#
 	# Configure vehicle type specific parameters.
-	# Note: rc.vehicle_setup is the entry point for rc.interface,
-	#       rc.fw_apps, rc.mc_apps, rc.rover_apps, and rc.vtol_apps.
-	#
+	# Note: rc.vehicle_setup is the entry point for all vehicle type specific setup.
 	. ${R}etc/init.d/rc.vehicle_setup
 
 	# Pre-takeoff continuous magnetometer calibration
 	if param compare -s MBE_ENABLE 1
 	then
 		mag_bias_estimator start
-	fi
-
-	if param greater -s TRIG_MODE 0
-	then
-		camera_trigger start
-		camera_feedback start
 	fi
 
 	#
@@ -428,26 +421,8 @@ else
 	#
 	. ${R}etc/init.d/rc.serial
 
-	if [ $IO_PRESENT = no ]
-	then
-		# Must be started after the serial config is read
-		rc_input start $RC_INPUT_ARGS
-	fi
-
-	# PPS capture driver (before pwm_out)
-	if param greater -s PPS_CAP_ENABLE 0
-	then
-		pps_capture start
-	fi
-
-	# Camera capture driver (before pwm_out)
-	if param greater -s CAM_CAP_FBACK 0
-	then
-		if camera_capture start
-		then
-			camera_capture on
-		fi
-	fi
+	# Must be started after the serial config is read
+	rc_input start $RC_INPUT_ARGS
 
 	#
 	# Play the startup tune (if not disabled or there is an error)
@@ -498,6 +473,12 @@ else
 		px4flow start -X &
 	fi
 
+	# Payload deliverer module if gripper is enabled
+	if param compare -s PD_GRIPPER_EN 1
+	then
+		payload_deliverer start
+	fi
+
 	#
 	# Optional board supplied extras: rc.board_extras
 	#
@@ -545,19 +526,14 @@ else
 	if param greater -s UAVCAN_ENABLE 0
 	then
 		# Start core UAVCAN module.
-		if uavcan start
+		if ! uavcan start
 		then
-			if param greater UAVCAN_ENABLE 2
-			then
-				set OUTPUT_MODE uavcan_esc
-			fi
-		else
 			tune_control play error
 		fi
 	else
-		if param greater -s UAVCAN_V1_ENABLE 0
+		if param greater -s CYPHAL_ENABLE 0
 		then
-			uavcan_v1 start
+			cyphal start
 		fi
 	fi
 
@@ -570,32 +546,19 @@ fi
 # Unset all script parameters to free RAM.
 #
 unset R
-unset AUTOCNF
 unset FCONFIG
 unset FEXTRAS
 unset FRC
-unset IO_PRESENT
 unset IOFW
 unset LOGGER_ARGS
 unset LOGGER_BUF
-unset MIXER
-unset MIXER_AUX
-unset MIXER_FILE
-unset OUTPUT_MODE
 unset PARAM_FILE
-unset PWM_AUX_OUT
-unset PWM_AUX_RATE
-unset PWM_MAIN_RATE
-unset PWM_OUT
-unset PWM_EXTRA_OUT
-unset PWM_EXTRA_RATE
+unset PARAM_BACKUP_FILE
 unset RC_INPUT_ARGS
 unset SDCARD_AVAILABLE
 unset SDCARD_EXT_PATH
 unset SDCARD_FORMAT
-unset SDCARD_MIXERS_PATH
 unset STARTUP_TUNE
-unset USE_IO
 unset VEHICLE_TYPE
 
 #
